project_name: "All_shells_cls"
path: ../Dataset/Classification_split

# Model Configurations
batch: 8
val: True
workers: 4
save: True
plots: True
epochs: 200
cos_lr: True
dropout: 0.3
resume: False
image_size: 512
save_period: 10
optimiser: "SGD"
