project_name: "All_shells_cls"
path: ../Dataset/Classification_split

# Model Configurations
epochs: 10
batch: 4
image_size: 512
save: True
save_period: 10
workers: 4
optimiser: "auto"
val: True
plots: True
resume: False